### ISSUE TITLE
Item-Updates and AWS-Topics logged in openhab.log, not events.log

### ISSUE THREAD

**Issue by KaaNee** [nibi79/worxlandroid#38] opened 2020-06-04 19:59 UTC
There's an excessive (much) logging in openhab.log for updates the thing/items are receiving and when AWSTopics are received.
This is all on INFO-Level.

From my opinion, these item-updates should be shown in the events.log (this is automatically as i know, if the item itself changes).
Perhabs change the log-level for these AWS-Messages, including the JSON of the Response in the log.

**Comment by nibi79** [comment] 2020-06-04 20:09
Duplicate of  #19

**Closed by nibi79** 2020-06-04 20:09 UTC
